Relations
annakynutsya/shop pull request #5
Opened 2023-02-12 14:15 UTC by annakynutsya

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/controllers/carts_controller.rb
> +      session[:cart] << params[:id]
а якщо такої айді не існує? І це по ідеї має бути product_id

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/controllers/carts_controller.rb
> +      session[:cart] << params[:id]
точніше продукту з таким ід

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/assets/stylesheets/components/nav.css
> +  .list-el {
пиши повну назву, не економ букви

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/controllers/orders_controller.rb
> +      @order.user_id = current_user.id
тут ще можна порефакторити

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/controllers/orders_controller.rb
> +      @order.user_id = current_user.id
без сетання юзера окремо

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/controllers/users/registrations_controller.rb
> +    # end
не треба? Видаляй

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/controllers/users/registrations_controller.rb
> +    Cart.create(user_id: current_user.id)
current_user.create_cart щось таке має працювати

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/controllers/users/sessions_controller.rb
> +      session[:cart] = Product.where(id: params[:id])
навіщо після розлогінювання зберігати продукти поточного юзера? А якщо я в друга на девайсі зайшов на свій ак глянути замовлення, потім вийшов, а він побачив що я замовив, а він не мав побачити, бо то наприклад подарунок йому на дн?

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/models/order.rb
> +  accepts_nested_attributes_for :order_detail
reject_if додай ще, всюди

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/views/carts/show.html.erb
> +      <%= "Your cart is empty. Let`s discover our assortiment!" %>
щось тут не так

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/views/shared_links/_navbar.html.erb
> +        <%= link_to (image_tag 'cart.png'), cart_path, method: :get, class: "cart-logo" %>
метод по дефолту буде get

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/views/shared_links/_navbar.html.erb
> +        <%= link_to (image_tag 'cart.png'), cart_path, method: :get, class: "cart-logo" %>
```suggestion
        <%= link_to image_tag('cart.png'), cart_path, method: :get, class: "cart-logo" %>
```

2023-02-12 23:22 UTC, VasylenchukMischa commented on app/views/shared_links/_navbar.html.erb
> +        <%= link_to (image_tag 'cart.png'), cart_path, class: "cart-logo" %>
тут теж поправ

2023-02-12 23:22 UTC, VasylenchukMischa commented on db/migrate/20230212140212_update_status_and_ordered_at_default_to_orders.rb
> +    change_column_default :orders, :ordered_at, from: nil, to: DateTime.now
може Time.now? А ще краще Time.zone.now?

2023-02-13 08:07 UTC, loqimean requested changes

2023-02-13 08:07 UTC, loqimean commented on Gemfile
> +gem 'simple_form'
сімпл форм має бути мого форку з теілвіндом, в чаті посилання буде

2023-02-13 08:07 UTC, loqimean commented on app/assets/stylesheets/components/nav.css
> +    @apply md:flex md:items-center md:z-auto md:static absolute bg-pink-500 w-full left-0 md:w-auto md:py-0 py-4 md:pl-0 pl-7 md:opacity-100 opacity-0 top-[-400px] transition-all ease-in duration-500
навіщо тобі `top-[-400px]`? перш за все мають бути `rem`, далі відʼємне значення в теілвінді пишеться не так і взагалі це має бути в конфігах, маю на увазі файл конфігів теілвінда

2023-02-13 08:07 UTC, loqimean commented on app/controllers/carts_controller.rb
> +      session[:cart] << params[:id]
ага

2023-02-13 08:07 UTC, loqimean commented on app/controllers/carts_controller.rb
> +      session[:cart] << params[:id]
і що, якщо така айдішка там вже є?

2023-02-13 08:07 UTC, loqimean commented on app/controllers/carts_controller.rb
> +    session[:cart] << params[:id]
має бути продук айді, чи ти туди карт закидаєш? бо я хз, ти в контролеррі карта знаходишся

2023-02-13 08:07 UTC, loqimean commented on app/controllers/orders_controller.rb
> +      @order.user_id = current_user.id
ну да, гуд заюзай рілейшини

2023-02-13 08:07 UTC, loqimean commented on app/controllers/orders_controller.rb
> +  def new
чому `new` у тебе нижче `create`?

2023-02-13 08:07 UTC, loqimean commented on app/controllers/orders_controller.rb
>    private
new line

2023-02-13 08:07 UTC, loqimean commented on app/controllers/orders_controller.rb
> +    params.require(:order).permit(:product_ids, order_detail_attributes: [:first_name, :last_name, :email, adress_attributes: [:country, :city, :street, :comment]])
looks better

2023-02-13 08:07 UTC, loqimean commented on app/controllers/users/registrations_controller.rb
> +    Cart.create(user_id: current_user.id)
yep

2023-02-13 08:07 UTC, loqimean commented on app/controllers/users/sessions_controller.rb
> +      session[:cart] = Product.where(id: params[:id])
аналогічне питання

2023-02-13 08:07 UTC, loqimean commented on app/controllers/users/sessions_controller.rb
> +      session[:cart] = Product.where(id: params[:id])
ну ріл думайте, що робите

2023-02-13 08:07 UTC, loqimean commented on app/models/adress.rb
> +  accepts_nested_attributes_for :order_detail
but where other options? what if they are blank and if record are saved but you provide empty options for it?

2023-02-13 08:07 UTC, loqimean commented on app/models/adress.rb
>    has_one :order_detail, dependent: :destroy
ти впевнений, що тут АДРЕСА належить деталям адреси, а не навпаки?

2023-02-13 08:07 UTC, loqimean commented on app/models/order.rb
> +  accepts_nested_attributes_for :order_detail
ага

2023-02-13 08:07 UTC, loqimean commented on app/models/order.rb
>    has_many :products, through: :product_orders, dependent: :destroy
воно точно працює?) бо мені здається ні, я такого коду ще ніде не бачив)

2023-02-13 08:07 UTC, loqimean commented on app/views/carts/show.html.erb
> +            <%= render 'shared_links/cart_product', product: product %>
які ще шарені лінки? давай тут в цій папці створи паршал на продукт та і всьо

2023-02-13 08:07 UTC, loqimean commented on app/views/carts/show.html.erb
> +            <%= render 'shared_links/cart_product', product: product %>
і назви норм

2023-02-13 08:07 UTC, loqimean commented on app/views/carts/show.html.erb
> +          <% @cart.each do |product| %>
не гуд, якщо це НЕ карт, то це НЕ карт, юзай тоді тут відразу сесії

2023-02-13 08:07 UTC, loqimean commented on app/views/carts/show.html.erb
> +      <%= "Your cart is empty. Let`s discover our assortiment!" %>
ага)

2023-02-13 08:07 UTC, loqimean commented on app/views/orders/new.html.erb
> +      <%= f.simple_fields_for :adress do |ff| %>
`af`, або ж `address_form`

2023-02-13 08:07 UTC, loqimean commented on app/views/products/show.html.erb
> +	<%= button_to 'Buy', add_product_to_cart_path, class: "btn-pink bg-pink-500 w-32 mt-6" %>
бекграунда тут точно не має бути

2023-02-13 08:07 UTC, loqimean commented on app/views/shared_links/_cart_product.html.erb
> +    <%= button_to 'Delete', remove_product_from_cart_path(product), method: :delete, class:'w-20 btn-pink bg-pink-500' %>
який ще деліт блін??

2023-02-13 08:07 UTC, loqimean commented on app/views/shared_links/_cart_product.html.erb
> +    <%= button_to 'Delete', remove_product_from_cart_path(product), method: :delete, class:'w-20 btn-pink bg-pink-500' %>
і бекграунда тут не повинно бути

2023-02-13 08:07 UTC, loqimean commented on app/views/shared_links/_cart_product.html.erb
> +    <%= link_to 'Show', product_path(product), class:'w-20 btn-pink bg-pink-500' %>
бек

2023-02-13 08:07 UTC, loqimean commented on app/views/shared_links/_navbar.html.erb
> +      <%= link_to (image_tag 'logo.png'), root_path, class: "w-32 cursor-pointer" %>
курсор і так мав би бути, а якщо ти його сетаєш, то перевір чи воно взагалі клікабельне

2023-02-13 08:07 UTC, loqimean commented on app/views/shared_links/_navbar.html.erb
> +        <%= link_to (image_tag 'cart.png'), cart_path, method: :get, class: "cart-logo" %>
ага

2023-02-13 08:07 UTC, loqimean commented on app/views/shared_links/_navbar.html.erb
> +        <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "btn-blue bg-cyan-500" %>
бек

2023-02-13 08:07 UTC, loqimean commented on app/views/shared_links/_navbar.html.erb
> +        <%= link_to 'Log in', new_user_session_path, class:"btn-blue bg-cyan-500"%>
знову юек

2023-02-13 08:07 UTC, loqimean commented on app/views/shared_links/_navbar.html.erb
> +        <%= link_to 'Log in', new_user_session_path, class:"btn-blue bg-cyan-500"%>
*бек

2023-02-13 08:07 UTC, loqimean commented on app/views/shared_links/_navbar.html.erb
> +        <%= link_to 'Sign up', new_user_registration_path, class:"btn-blue bg-cyan-500"%>
скрізь беку не повинно бути, якщо у тебе це компонента кнопки

2023-02-13 08:07 UTC, loqimean commented on app/views/shared_links/_navbar.html.erb
> +        <%= link_to (image_tag 'cart.png'), cart_path, class: "cart-logo" %>
та скрізь так

2023-02-13 08:07 UTC, loqimean commented on db/migrate/20230212140212_update_status_and_ordered_at_default_to_orders.rb
> +    change_column_default :orders, :ordered_at, from: nil, to: DateTime.now
мона простіше, `DateTime.current`, це юзай

2023-02-14 18:50 UTC, loqimean commented on config/routes.rb
> +  resources :carts do
це має бути ресурс

2023-02-14 18:50 UTC, loqimean commented on config/routes.rb
> +      patch :remove_product_from
і тут має передаватися констрейнт `product_id`

2023-02-14 18:50 UTC, loqimean commented on config/routes.rb
> +  resources :carts do
і чому у тебе дублювання?

2023-02-14 18:50 UTC, loqimean commented on db/migrate/20230213213710_update_ordered_at_default_to_orders.rb
> +    change_column_default :orders, :ordered_at, from: nil, to: DateTime.current
воно гуд працює? ну дата гуд ставиться?

2023-02-14 18:50 UTC, loqimean commented on app/views/products/show.html.erb
> +	<%= button_to 'Buy', add_product_to_cart_path, class: "btn-pink w-32 mt-6" %>
а як ти що і куда передаєш?

2023-02-14 18:50 UTC, loqimean commented on app/views/layouts/application.html.erb
> +
видаляй

2023-02-14 18:50 UTC, loqimean commented on app/views/carts/show.html.erb
> +        <%= render 'carts/cart_product', product: product %>
назва паршалу не гуд

2023-02-14 18:50 UTC, loqimean commented on app/views/carts/show.html.erb
> +        <%= render 'carts/cart_product', product: product %>
назва

2023-02-14 18:50 UTC, loqimean commented on app/views/carts/show.html.erb
> +        <%= render 'carts/cart_product', product: product %>
паршала

2023-02-14 18:50 UTC, loqimean commented on app/models/order_detail.rb
> +  accepts_nested_attributes_for :adress
реджекти, деліти і тд

2023-02-14 18:50 UTC, loqimean commented on app/models/order.rb
> +  accepts_nested_attributes_for :order_detail
досі нема

2023-02-14 18:50 UTC, loqimean commented on app/controllers/users/sessions_controller.rb
> +      current_user.cart.products << Product.where(id: session[:product_ids])
перенеси це в афтер екшин і там то зроби

2023-02-14 18:50 UTC, loqimean commented on app/controllers/users/registrations_controller.rb
> +    current_user.cart.products << Product.where(id: session[:product_ids])
афтер екшин

2023-02-14 18:50 UTC, loqimean commented on app/controllers/orders_controller.rb
> +      @order = Order.new(order_params.merge(product_ids: current_user.cart.products.destroy_all.pluck(:id), user_id: current_user.id))
рілейшини

2023-02-14 18:50 UTC, loqimean commented on app/controllers/carts_controller.rb
> +    session[:product_ids] << params[:id]
спрости

2023-02-14 18:50 UTC, loqimean commented on app/controllers/carts_controller.rb
> +    end
щось не так)

2023-02-14 18:50 UTC, loqimean commented on app/controllers/carts_controller.rb
>      end
```suggestion
    end

```

2023-02-14 18:50 UTC, loqimean commented on app/controllers/carts_controller.rb
>      end
```suggestion
    end

```

2023-03-04 13:32 UTC, mykhailovasylenchuk commented on app/assets/stylesheets/components/buttons.css
> +    @apply text-white bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-pink-300 dark:focus:ring-pink-800 shadow-lg shadow-pin
```suggestion
    @apply text-white bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600
     hover:bg-gradient-to-br focus:ring-4 
     focus:outline-none focus:ring-pink-300 
     dark:focus:ring-pink-800 shadow-lg shadow-pink-500/50 dark:shadow-lg dark:shadow-pink-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2;
```

2023-03-04 13:33 UTC, mykhailovasylenchuk commented on app/assets/stylesheets/components/buttons.css
> +    @apply text-white bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-pink-300 dark:focus:ring-pink-800 shadow-lg shadow-pin
перенеси одним словом щоб не в одну лінію

2023-03-04 13:33 UTC, mykhailovasylenchuk commented on app/assets/stylesheets/components/buttons.css
> +    @apply text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px
всюди

2023-05-04 20:37 UTC, merged